In [1]:
import pandas as pd
from unidecode import unidecode
import numpy as np

In [2]:
convert_muni = pd.read_csv('https://raw.githubusercontent.com/ekatovich/Municipality_Name_ID_crosswalk/master/Raw_Brazil_GeographicalUnits.csv', encoding='latin-1')
convert_muni = convert_muni[['uf', 'uf_name', 'mesoregion_stub', 'mesoregion_name',
       'microregion_stub', 'microregion_name', 'munic_stub', 'munic_code',
       'munic_name']]
convert_muni.munic_code = convert_muni.munic_code.astype(str)
convert_muni.munic_name = convert_muni.munic_name.apply(unidecode).apply(lambda x: x.lower())
convert_muni.munic_name = convert_muni.munic_name.apply(lambda x: x.replace('\'', '').replace(' ', ''))
convert_muni.head()

,uf,uf_name,mesoregion_stub,mesoregion_name,microregion_stub,microregion_name,munic_stub,munic_code,munic_name
0,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,altaflorestadoeste
1,11,Rondônia,2,Leste Rondoniense,6,Cacoal,379,1100379,altoalegredosparecis
2,11,Rondônia,2,Leste Rondoniense,3,Ariquemes,403,1100403,altoparaiso
3,11,Rondônia,2,Leste Rondoniense,5,Alvorada D'Oeste,346,1100346,alvoradadoeste
4,11,Rondônia,2,Leste Rondoniense,3,Ariquemes,23,1100023,ariquemes

In [3]:

df = pd.read_csv('/Users/annieulichney/Downloads/votacao_candidato_munzona_2016-2/votacao_candidato_munzona_2016_BRASIL.csv',  delimiter=';', encoding='latin1')
cols = ['ANO_ELEICAO', 'NR_TURNO', 'NM_TIPO_ELEICAO', 'SG_UF', 'CD_MUNICIPIO', 'DS_CARGO', 'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_UE', 'DS_SIT_TOT_TURNO', 'QT_VOTOS_NOMINAIS', 'SG_PARTIDO']


df = df[cols]

df.NM_TIPO_ELEICAO = df.NM_TIPO_ELEICAO.apply(unidecode).apply(lambda x: x.lower())
df.DS_CARGO = df.DS_CARGO.apply(unidecode).apply(lambda x: x.lower())
df.NM_UE = df.NM_UE.apply(unidecode).apply(lambda x: x.lower())
df.DS_SIT_TOT_TURNO = df.DS_SIT_TOT_TURNO.apply(unidecode).apply(lambda x: x.lower())
df.NM_UE = df.NM_UE.apply(lambda x: x.replace('\'', '').replace(' ', ''))

In [4]:
#np.savetxt('nm_ue.txt', np.unique(df.NM_UE),fmt='%s')

In [ ]:
#don't change
replace = ['acucena', 'apicum-acu', 'aracu', 'aracuai', 'araguacu',
       'babaculandia', 'bacuri', 'bacurituba', 'biguacu',
       'boaesperancadoiguacu', 'cabaceirasdoparaguacu',
       'cachoeirasdemacacu', 'cacu', 'cacule', 'campinacu', 'careacu',
       'caririacu', 'conceicaodojacuipe', 'conceicaodolago-acu',
       'cotriguacu', 'cruzeirodoiguacu', 'embu-guacu',
       'espigaoaltodoiguacu', 'euclidesdacunha',
       'euclidesdacunhapaulista', 'floresdacunha', 'fozdoiguacu',
       'guacui', 'guapiacu', 'guaraniacu', 'iacu', 'ibiracu',
       'igaracudotiete', 'igarape-acu', 'iguaracu', 'imaculada',
       'ipanguacu', 'ipiacu', 'ipuacu', 'itacuruba', 'itacurubi',
       'itaguacu', 'itaguacudabahia', 'itambacuri', 'ituacu', 'jacui',
       'jacuipe', 'jacuizinho', 'jacunda', 'jacupiranga', 'jacutinga',
       'jaguaracu', 'macuco', 'macurure', 'mandaguacu', 'manhuacu',
       'maracacume', 'minacu', 'mogiguacu', 'novaiguacu',
       'novaiguacudegoias', 'novapratadoiguacu', 'pacuja', 'paodeacucar',
       'paracuru', 'paraguacu', 'paraguacupaulista', 'pariquera-acu',
       'pindobacu', 'piracuruca', 'pracuuba', 'quedasdoiguacu',
       'reservadoiguacu', 'riachaodojacuipe', 'riobonitodoiguacu',
       'saltodojacui', 'santamariadosuacui', 'santanadomanhuacu',
       'santaritadejacutinga', 'saobrasdosuacui', 'saojoaodomanhuacu',
       'saojoaodopacui', 'saojosedojacuipe', 'saojosedojacuri',
       'saomigueldoiguacu', 'saopedrodoiguacu', 'saopedrodosuacui',
       'sapeacu', 'saudadedoiguacu', 'serranopolisdoiguacu', 'tacuru',
       'taiacu', 'tanhacu', 'taquaracudeminas', 'tome-acu', 'tracuateua',
       'tracunhaem', 'turiacu', 'uruacu']

    #change
    original_wrong = ['acucena', 'apicum-acu', 'aracu', 'aracuai', 'araguacu',
       'babaculandia', 'bacuri', 'bacurituba', 'biguacu',
       'boaesperancadoiguacu', 'cabaceirasdoparaguacu',
       'cachoeirasdemacacu', 'cacu', 'cacule', 'campinacu', 'careacu',
       'caririacu', 'conceicaodojacuipe', 'conceicaodolago-acu',
       'cotriguacu', 'cruzeirodoiguacu', 'embu-guacu',
       'espigaoaltodoiguacu', 'euclidesdacunha',
       'euclidesdacunhapaulista', 'floresdacunha', 'fozdoiguacu',
       'guacui', 'guapiacu', 'guaraniacu', 'iacu', 'ibiracu',
       'igaracudotiete', 'igarape-acu', 'iguaracu', 'imaculada',
       'ipanguacu', 'ipiacu', 'ipuacu', 'itacuruba', 'itacurubi',
       'itaguacu', 'itaguacudabahia', 'itambacuri', 'ituacu', 'jacui',
       'jacuipe', 'jacuizinho', 'jacunda', 'jacupiranga', 'jacutinga',
       'jaguaracu', 'macuco', 'macurure', 'mandaguacu', 'manhuacu',
       'maracacume', 'minacu', 'mogiguacu', 'novaiguacu',
       'novaiguacudegoias', 'novapratadoiguacu', 'pacuja', 'paodeacucar',
       'paracuru', 'paraguacu', 'paraguacupaulista', 'pariquera-acu',
       'pindobacu', 'piracuruca', 'pracuuba', 'quedasdoiguacu',
       'reservadoiguacu', 'riachaodojacuipe', 'riobonitodoiguacu',
       'saltodojacui', 'santamariadosuacui', 'santanadomanhuacu',
       'santaritadejacutinga', 'saobrasdosuacui', 'saojoaodomanhuacu',
       'saojoaodopacui', 'saojosedojacuipe', 'saojosedojacuri',
       'saomigueldoiguacu', 'saopedrodoiguacu', 'saopedrodosuacui',
       'sapeacu', 'saudadedoiguacu', 'serranopolisdoiguacu', 'tacuru',
       'taiacu', 'tanhacu', 'taquaracudeminas', 'tome-acu', 'tracuateua',
       'tracunhaem', 'turiacu', 'uruacu']

In [5]:
#these are the ones in convert, they do not change!
replace = ['alvoradadooeste', 'assu', 'boasaude', 'camaca',
       'eldoradodoscarajas', 'espigaodooeste', 'gracchocardoso',
       'grao-para', 'olhosdagua', 'quinjingue', 'santaisabeldopara',
       'saoluisdoparaitinga', 'sempeixe']

#these are the ones we want to replace them with, change them to the way it's spelled in df not convert_muni!
original_wrong = ['alvoradadoeste', 'acu', 'januariocicco', 'camacan',
       'eldoradodocarajas', 'espigaodoeste', 'grachocardoso',
       'graopara', 'olhos-dagua', 'quijingue', 'santaizabeldopara',
       'saoluizdoparaitinga', 'sem-peixe']

In [6]:
for i in range(len(original_wrong)):
    old = original_wrong[i]
    new = replace[i]
    convert_muni = convert_muni.replace({old: new}, regex=True)

In [7]:
df = pd.merge(df, convert_muni[['munic_name', 'munic_code']], how = 'left', left_on = ['NM_UE'], right_on = ['munic_name'])

In [13]:
df[df.NM_UE == 'biguacu']

,ANO_ELEICAO,NR_TURNO,NM_TIPO_ELEICAO,SG_UF,CD_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_UE,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS,SG_PARTIDO,munic_name,munic_code
789421,2016,1,eleicao ordinaria,SC,80454,prefeito,240000003089,50,biguacu,nao eleito,2145,PSOL,NaN,NaN
789422,2016,1,eleicao ordinaria,SC,80454,prefeito,240000009813,55,biguacu,eleito,17618,PSD,NaN,NaN
789423,2016,1,eleicao ordinaria,SC,80454,prefeito,240000005147,15,biguacu,nao eleito,17535,PMDB,NaN,NaN
789424,2016,1,eleicao ordinaria,SC,80454,vereador,240000005267,15113,biguacu,suplente,352,PMDB,NaN,NaN
789425,2016,1,eleicao ordinaria,SC,80454,vereador,240000005210,12222,biguacu,suplente,22,PDT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789570,2016,1,eleicao ordinaria,SC,80454,vereador,240000005206,77015,biguacu,suplente,66,SD,NaN,NaN
789571,2016,1,eleicao ordinaria,SC,80454,vereador,240000005198,77303,biguacu,suplente,146,SD,NaN,NaN
789572,2016,1,eleicao ordinaria,SC,80454,vereador,240000003097,50007,biguacu,nao eleito,28,PSOL,NaN,NaN
789573,2016,1,eleicao ordinaria,SC,80454,vereador,240000005738,25035,biguacu,suplente,43,DEM,NaN,NaN
789574,2016,1,eleicao ordinaria,SC,80454,vereador,240000017087,11011,biguacu,suplente,365,PP,NaN,NaN

In [8]:
np.unique(df[df.munic_name.isna()].NM_UE)

array(['acucena', 'apicum-acu', 'aracu', 'aracuai', 'araguacu',
       'babaculandia', 'bacuri', 'bacurituba', 'biguacu',
       'boaesperancadoiguacu', 'cabaceirasdoparaguacu',
       'cachoeirasdemacacu', 'cacu', 'cacule', 'campinacu', 'careacu',
       'caririacu', 'conceicaodojacuipe', 'conceicaodolago-acu',
       'cotriguacu', 'cruzeirodoiguacu', 'embu-guacu',
       'espigaoaltodoiguacu', 'euclidesdacunha',
       'euclidesdacunhapaulista', 'floresdacunha', 'fozdoiguacu',
       'guacui', 'guapiacu', 'guaraniacu', 'iacu', 'ibiracu',
       'igaracudotiete', 'igarape-acu', 'iguaracu', 'imaculada',
       'ipanguacu', 'ipiacu', 'ipuacu', 'itacuruba', 'itacurubi',
       'itaguacu', 'itaguacudabahia', 'itambacuri', 'ituacu', 'jacui',
       'jacuipe', 'jacuizinho', 'jacunda', 'jacupiranga', 'jacutinga',
       'jaguaracu', 'macuco', 'macurure', 'mandaguacu', 'manhuacu',
       'maracacume', 'minacu', 'mogiguacu', 'novaiguacu',
       'novaiguacudegoias', 'novapratadoiguacu', 'pacuja', 'paodeacucar',
       'paracuru', 'paraguacu', 'paraguacupaulista', 'pariquera-acu',
       'pindobacu', 'piracuruca', 'pracuuba', 'quedasdoiguacu',
       'reservadoiguacu', 'riachaodojacuipe', 'riobonitodoiguacu',
       'saltodojacui', 'santamariadosuacui', 'santanadomanhuacu',
       'santaritadejacutinga', 'saobrasdosuacui', 'saojoaodomanhuacu',
       'saojoaodopacui', 'saojosedojacuipe', 'saojosedojacuri',
       'saomigueldoiguacu', 'saopedrodoiguacu', 'saopedrodosuacui',
       'sapeacu', 'saudadedoiguacu', 'serranopolisdoiguacu', 'tacuru',
       'taiacu', 'tanhacu', 'taquaracudeminas', 'tome-acu', 'tracuateua',
       'tracunhaem', 'turiacu', 'uruacu'], dtype=object)

In [47]:
convert_muni[convert_muni.munic_name == 'acu']

,uf,uf_name,mesoregion_stub,mesoregion_name,microregion_stub,microregion_name,munic_stub,munic_code,munic_name
1076,24,Rio Grande do Norte,1,Oeste Potiguar,4,Vale do Açu,208,2400208,acu

In [12]:
df

,ANO_ELEICAO,NR_TURNO,NM_TIPO_ELEICAO,SG_UF,CD_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_UE,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS,SG_PARTIDO,munic_name,munic_code
0,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002509,45,acrelandia,nao eleito,627,PSDB,acrelandia,1200013
1,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002445,40,acrelandia,eleito,3852,PSB,acrelandia,1200013
2,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001075,11,acrelandia,nao eleito,1545,PP,acrelandia,1200013
3,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002100,10,acrelandia,nao eleito,259,PRB,acrelandia,1200013
4,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001284,12,acrelandia,nao eleito,886,PDT,acrelandia,1200013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025507,2016,2,eleicao ordinaria,SP,70750,prefeito,250000010056,45,saobernardodocampo,eleito,34691,PSDB,saobernardodocampo,3548708
1025508,2016,2,eleicao ordinaria,SP,70750,prefeito,250000013230,23,saobernardodocampo,nao eleito,34438,PPS,saobernardodocampo,3548708
1025509,2016,2,eleicao ordinaria,SP,70750,prefeito,250000010056,45,saobernardodocampo,eleito,42241,PSDB,saobernardodocampo,3548708
1025510,2016,2,eleicao ordinaria,SP,70750,prefeito,250000013230,23,saobernardodocampo,nao eleito,17126,PPS,saobernardodocampo,3548708
1025511,2016,2,eleicao ordinaria,SP,70750,prefeito,250000010056,45,saobernardodocampo,eleito,30476,PSDB,saobernardodocampo,3548708

In [313]:
df['id_municipio_tse'] = np.nan
df['id_candidato_bd'] = np.nan

#df['sigla_partido'] = np.nan

In [ ]:
vote1.head()

In [314]:
df.head()

,ANO_ELEICAO,NR_TURNO,NM_TIPO_ELEICAO,SG_UF,CD_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_UE,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS,SG_PARTIDO,munic_name,munic_code,id_municipio_tse,id_candidato_bd
0,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002509,45,acrelandia,nao eleito,627,PSDB,acrelandia,1200013,NaN,NaN
1,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002445,40,acrelandia,eleito,3852,PSB,acrelandia,1200013,NaN,NaN
2,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001075,11,acrelandia,nao eleito,1545,PP,acrelandia,1200013,NaN,NaN
3,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002100,10,acrelandia,nao eleito,259,PRB,acrelandia,1200013,NaN,NaN
4,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001284,12,acrelandia,nao eleito,886,PDT,acrelandia,1200013,NaN,NaN

In [316]:
['ano', 'turno', 'tipo_eleicao', 'sigla_uf', 'id_municipio',
       'id_municipio_tse', 'cargo', 'sigla_partido', 'numero_candidato',
       'sequencial_candidato', 'id_candidato_bd', 'resultado', 'votos']

['ano',
 'turno',
 'tipo_eleicao',
 'sigla_uf',
 'id_municipio',
 'id_municipio_tse',
 'cargo',
 'sigla_partido',
 'numero_candidato',
 'sequencial_candidato',
 'id_candidato_bd',
 'resultado',
 'votos']

In [322]:
df.columns = ['ano', 'turno', 'tipo_eleicao', 'sigla_uf', 'id_municipio_old',
       'cargo', 'sequencial_candidato', 'numero_candidato', 'munic_name', 'resultado',
       'votos', 'sigla_partido', 'munic_name', 'id_municipio',  'id_municipio_tse', 'id_candidato_bd']

In [323]:
df = df.loc[:,~df.columns.duplicated()].copy()

In [324]:
df.head()

,ano,turno,tipo_eleicao,sigla_uf,id_municipio_old,cargo,sequencial_candidato,numero_candidato,munic_name,resultado,votos,sigla_partido,id_municipio,id_municipio_tse,id_candidato_bd
0,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002509,45,acrelandia,nao eleito,627,PSDB,1200013,NaN,NaN
1,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002445,40,acrelandia,eleito,3852,PSB,1200013,NaN,NaN
2,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001075,11,acrelandia,nao eleito,1545,PP,1200013,NaN,NaN
3,2016,1,eleicao ordinaria,AC,1120,prefeito,10000002100,10,acrelandia,nao eleito,259,PRB,1200013,NaN,NaN
4,2016,1,eleicao ordinaria,AC,1120,prefeito,10000001284,12,acrelandia,nao eleito,886,PDT,1200013,NaN,NaN

In [325]:
np.unique(df[df.id_municipio.isna()].munic_name)

array(['assu', 'assuncao', 'assuncaodopiaui', 'bataguassu', 'ibiassuce',
       'igarassu', 'pirassununga'], dtype=object)

In [330]:
len(np.unique(df[~df.id_municipio.astype(int, errors = 'ignore').isna()].id_municipio))

5559

In [230]:
#np.savetxt('munic_names.txt', np.unique(convert_muni.munic_name), fmt='%s')

In [329]:
df = df[['ano', 'turno', 'tipo_eleicao', 'sigla_uf', 'id_municipio',
       'id_municipio_tse', 'cargo', 'sigla_partido', 'numero_candidato',
       'sequencial_candidato', 'id_candidato_bd', 'resultado', 'votos']]

In [331]:
df.head()

,ano,turno,tipo_eleicao,sigla_uf,id_municipio,id_municipio_tse,cargo,sigla_partido,numero_candidato,sequencial_candidato,id_candidato_bd,resultado,votos
0,2016,1,eleicao ordinaria,AC,1200013,NaN,prefeito,PSDB,45,10000002509,NaN,nao eleito,627
1,2016,1,eleicao ordinaria,AC,1200013,NaN,prefeito,PSB,40,10000002445,NaN,eleito,3852
2,2016,1,eleicao ordinaria,AC,1200013,NaN,prefeito,PP,11,10000001075,NaN,nao eleito,1545
3,2016,1,eleicao ordinaria,AC,1200013,NaN,prefeito,PRB,10,10000002100,NaN,nao eleito,259
4,2016,1,eleicao ordinaria,AC,1200013,NaN,prefeito,PDT,12,10000001284,NaN,nao eleito,886

In [332]:
df.id_municipio.value_counts()

3304557    148410
3550308     70528
3106200     24840
2927408     18980
1302603     16926
            ...
4213153        11
4312179        11
2406908        10
3516408         4
3522307         4
Name: id_municipio, Length: 5559, dtype: int64

In [267]:
df.to_csv('election_results_2016.csv', index = False)

In [ ]:
df